[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "avtomatika-worker"
version = "1.0b13"
description = "Worker SDK for the Avtomatika orchestrator."
readme = "README.md"
requires-python = ">=3.11"
authors = [
    {name = "Dmitrii Gagarin", email = "madgagarin@gmail.com"},
]
keywords = ["worker", "sdk", "orchestrator", "distributed", "task-queue", "rxon", "hln"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
    "Operating System :: OS Independent",
    "Typing :: Typed",
]
dependencies = [
    "rxon==1.0b7",
    "aiohttp~=3.13.5",
    "python-json-logger~=4.1.0",
    "aiofiles~=25.1.0",
    "orjson~=3.10.15",
]

[project.scripts]
worker = "avtomatika_worker.__main__:main"

[project.optional-dependencies]
s3 = ["obstore~=0.9.2"]
pydantic = ["pydantic~=2.12"]
metrics = [
    "opentelemetry-api~=1.30.0",
    "opentelemetry-sdk~=1.30.0",
    "opentelemetry-semantic-conventions~=0.50b0",
    "opentelemetry-exporter-prometheus~=0.50b0",
]
test = [
    "avtomatika-worker[s3,pydantic]",
    "pytest",
    "pytest-asyncio",
    "aioresponses",
    "pytest-mock",
    "types-aiofiles",
]
dev = [
    "avtomatika-worker[test]",
    "watchdog",
]

[project.urls]
"Homepage" = "https://github.com/avtomatika-ai/avtomatika-worker"
"Bug Tracker" = "https://github.com/avtomatika-ai/avtomatika-worker/issues"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"avtomatika_worker" = ["py.typed"]

[tool.pytest.ini_options]
markers = [
    "e2e: marks tests as end-to-end tests",
]
pythonpath = "src"
filterwarnings = [
    "ignore:'asyncio.iscoroutinefunction' is deprecated:DeprecationWarning",
    "ignore:coroutine 'AsyncMockMixin._execute_mock_call' was never awaited:RuntimeWarning",
    "ignore::pytest.PytestUnraisableExceptionWarning"
]

[tool.ruff]
src = ["src", "tests"]
target-version = "py311"
line-length = 120

[tool.ruff.lint]
select = ["E", "W", "F", "I", "B", "A", "SIM", "C4", "PLC2401", "UP", "TID"]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "parents"

[tool.ruff.lint.flake8-tidy-imports.banned-api]
"json".msg = "Use 'orjson' instead of standard 'json' for better performance."

[tool.ruff.lint.pyupgrade]
# Enforce native union types (X | Y) instead of Union/Optional
keep-runtime-typing = false

[tool.ruff.lint.isort]
known-first-party = ["avtomatika_worker"]

[tool.ruff.format]
quote-style = "double"
skip-magic-trailing-comma = false

[tool.mypy]
python_version = "3.11"
packages = ["avtomatika_worker"]
disallow_incomplete_defs = true
disallow_untyped_calls = true
no_implicit_optional = true
ignore_missing_imports = true
follow_imports = "skip"
warn_unused_ignores = true
warn_return_any = true
disallow_any_unimported = false
exclude = ["tests/"]

[tool.coverage.run]
source = ["src/avtomatika_worker"]
